//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhLuong
    {
        public int IdCauHinh { get; set; }
        public string ChucVu { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public Nullable<decimal> PhuCapChucVu { get; set; }
        public Nullable<decimal> PhuCapAnTrua { get; set; }
        public Nullable<decimal> PhuCapXangXe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Disabled { get; set; }
    }
}
