//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong_SanPham
    {
        public int IDDPSP { get; set; }
        public int IdDatPhong { get; set; }
        public Nullable<int> IdPhong { get; set; }
        public Nullable<int> IdSP { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> IdDPCT { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
