//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.DatPhong_ChiTiet = new HashSet<DatPhong_ChiTiet>();
            this.DatPhong_SanPham = new HashSet<DatPhong_SanPham>();
        }
    
        public int IdDatPhong { get; set; }
        public int IdKH { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public Nullable<int> SoNguoiO { get; set; }
        public int UId { get; set; }
        public string MaCTY { get; set; }
        public string MaDVI { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> TheoDoan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string PhuongThucThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong_ChiTiet> DatPhong_ChiTiet { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong_SanPham> DatPhong_SanPham { get; set; }
        public virtual User User { get; set; }
    }
}
