//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUAN_LI_KHACH_SANEntities : DbContext
    {
        public QUAN_LI_KHACH_SANEntities()
            : base("name=QUAN_LI_KHACH_SANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Func> Funcs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CongTy> CongTies { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Phong_ThietBi> Phong_ThietBi { get; set; }
        public virtual DbSet<Tang> Tangs { get; set; }
        public virtual DbSet<Param> Params { get; set; }
        public virtual DbSet<DatPhong_ChiTiet> DatPhong_ChiTiet { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
        public virtual DbSet<DatPhong_SanPham> DatPhong_SanPham { get; set; }
        public virtual DbSet<DatPhong> DatPhongs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    }
}
