//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param
    {
        public string MaCTY { get; set; }
        public string MaDVI { get; set; }
        public string TenCTY { get; set; }
        public string TenDVI { get; set; }
    
        public virtual CongTy CongTy { get; set; }
        public virtual DonVi DonVi { get; set; }
    }
}
