//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DatPhong_ChiTiet = new HashSet<DatPhong_ChiTiet>();
            this.DatPhong_SanPham = new HashSet<DatPhong_SanPham>();
            this.Phong_ThietBi = new HashSet<Phong_ThietBi>();
        }
    
        public int IdPhong { get; set; }
        public string TenPhong { get; set; }
        public string TrangThai { get; set; }
        public int IdTang { get; set; }
        public int IdLoaiPhong { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong_ChiTiet> DatPhong_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong_SanPham> DatPhong_SanPham { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual Tang Tang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_ThietBi> Phong_ThietBi { get; set; }
    }
}
