//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_ThietBi
    {
        public int IdPhong { get; set; }
        public int IdThietBi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual ThietBi ThietBi { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
