//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int UId { get; set; }
        public string FullName { get; set; }
        public string Passwd { get; set; }
        public string MaCTY { get; set; }
        public string MaDVI { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual CongTy CongTy { get; set; }
        public virtual DonVi DonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
    }
}
